name: test

on:
  push:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader -d ./update
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@b649ad206d2e83dafb9ed130deba698aa1b41d78 # v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          workingDirectory: update/
          coverageCommand: vendor/bin/phpunit
          coverageLocations: build/logs/clover.xml:clover
